### ISSUE TITLE
Internal Server error in Backend

### ISSUE THREAD

**Issue by sfx12** [pdir/social-feed-bundle#10]
Hallo,

ich bekomme folgenden Fehler im Backend nach dem einrichten eines accounts:
**#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.**

Laut eurer Doku ist es doch nicht notwendig wenn man ADMIN der Fanpage ist, einen review zu machen !?

**Comment by seibtph** [comment]
Man muss Admin der Fanpage sein, ansonsten muss die App erst zum App Review eingereicht werden, was etwas komplizierter ist.

In der Doku steht unter Einrichtung bei Facebook-App anlegen: _Wenn Sie Beiträge einer Facebook-Seite, von der Sie nicht Admin sind, anzeigen lassen wollen, müssen Sie die Facebook App erst zum App Review einreichen. Für die eigene Facebook Seite ist dies nicht notwendig._

https://docs.pdir.de/#/social-feed/einrichtung-facebook-stream

**Comment by sfx12** [comment]
Ich hab doch in meinem Beitrag geschrieben das ich ADMIN der Page bin!!!

**Comment by seibtph** [comment]
Sorry, hatte nicht gesehen, dass beide Tickets zusammengehören. Antwort hier: #9
