### ISSUE TITLE
Refresh instagram token via cronjob

### ISSUE THREAD

**Issue by falkgeist** [pdir/social-feed-bundle#106]
## Description
At the moment, long-lived instagram tokens expire after 60 days, making it necessary to create a new token about every two months. This is tedious, tbh.

Is there a possiblity to add a cronjob to the bundle, that refreshes the token after e.g. 30 days via the corresponding endpoint of the Basic Display API?

[Long lived access tokens](https://developers.facebook.com/docs/instagram-basic-display-api/guides/long-lived-access-tokens/)

We already got several clients calling, asking why the feed is not showing posts anymore...

Thank you very much!

**Comment by falkgeist** [comment]
That sounds perfect, I will check in the corresponding installation when I find the time.

**Comment by seibtph** [comment]
So I will close the issue. If you have another problems with that you can reopen the issue.
