### ISSUE TITLE
Bilder von Facebook laden nicht

### ISSUE THREAD

**Issue by elvirgit** [pdir/social-feed-bundle#108]
Ich verwende das Contao-Plugin, um Facebook-Beiträge auf einer Website aufzulisten. Alles funktioniert, Beiträge werden geladen, nur Bilder fehlen. Habe ich etwas vergessen einzustellen oder liegt es an etwas anderem?
Hier ist ein Screenshot:
![feed-soc-eror](https://user-images.githubusercontent.com/56090835/227793013-d5fdfc73-5215-4f6f-b32c-5eba9932755b.jpg)

**Comment by seibtph** [comment]
Ich schließe das Ticket mal. Wenn das Problem noch auftritt, gern nochmal melden. Möglicherweise ist der Ordner in der Dateiverwaltung auch nicht auf öffentlich gestellt?
