### ISSUE TITLE
Linkedin wrong URI when generatin access token

### ISSUE THREAD

**Issue by arboc** [pdir/social-feed-bundle#110]
## Bug description
we want to implement linkedin.  
we followed the instructions.  
when we want to generate the access toke, we got an error from linkedin:

![image](https://user-images.githubusercontent.com/4447843/233597995-e76cba02-673b-472b-a3d2-cf72ea3d03b2.png)

## Steps to reproduce
Create a social feed account for linkedin.
Try to generate an access token

![image](https://user-images.githubusercontent.com/4447843/233598601-e51e118a-5ae9-4fc8-9c15-55dbc632f9a2.png)

## Expected behavior
get an access token

## Screenshots
s.o.

## Bundle Version
2.12.0

## Environment
Debian, PHP7.4, Contao 4.9.39

**Comment by seibtph** [comment]
You need to add a redirect URL for your app (https://your-domain/auth/linkedin).

![linkedin_12](https://user-images.githubusercontent.com/17127525/233618840-05b8da93-179b-42fb-bab4-bf2bf88fd436.png)
