### ISSUE TITLE
Kein Import Twitter / Debug-Optionen?

### ISSUE THREAD

**Issue by johannes-bittner** [pdir/social-feed-bundle#113]
Ich nutze Version 2.12 auf Contao 4.13.23 / PHP 8.1, bekomme aber keinen Import von Twitter und auch keine Fehlermeldung. Die Einstellungen im Twitter Developer-Account haben sich gegenüber der Doku ja auch geändert, aber es passiert einfach nichts. Ich nehme an, dass man weiterhin API Key und Secret aus dem Abschnitt Consumer Keys sowie Access Token und Secret aus dem Abschnitt Authentication Tokens nehmen muss (?). Hat jemand Erfahrungen, an welcher Stelle man für die Fehlersuche ansetzen kann?

![grafik](https://user-images.githubusercontent.com/1597697/236141175-e7a8a69d-b335-4e4d-ace5-5e6c586d8145.png)

**Comment by seibtph** [comment]
Wie sehen deine Einstellungen im Backend aus? Die richtigen Daten sind es. Du kannst sie mir auch mal per Mail an support [AT] pdir . de senden, dann könnte ich mal testen ob irgendwelche Daten oder eine Fehlermeldung ankommt.

**Comment by johannes-bittner** [comment]
Hier das Backend: 
![grafik](https://user-images.githubusercontent.com/1597697/236771327-e4710da7-b321-4058-b772-66b51fde89a8.png)
Keys und Token habe ich geprüft, die stimmen (sind auch keine Leerzeichen am Anfang/Ende o.ä.). Änderung der Optionen (Retweets/Hashtags) macht auch keinen Unterschied. Im Log findet sich auch nichts. Müsste der Cronjob in der tl_cron_job gelistet sein?

**Comment by seibtph** [comment]
Am besten du schickst mir mal die Social Feed Daten per Mail. Also API Key, API Secret Key, Access Token, Access Token Secret und den Accountnamen. Dann könnte ich schauen ob irgendwelche Daten von Twitter zurückkommen oder irgendeine Fehlermeldung kommt.

**Comment by klimeckt** [comment]
Den Eindruck habe ich auch. Mein Konto wurde gesperrt wegen des Abrufens zweier Projekte. Ich habe dann eins der Projekte mit dem eigentlichen Twitter Account konfiguriert und alle Daten im Social Feed eingetragen. Leider passiert damit aber nichts. Im Logfile sehe ich allerdings diese Fehlermeldung:
request.CRITICAL: Uncaught PHP Exception TypeError: "file_get_contents(): Argument #1 ($filename) must be of type string, null given" at

**Comment by klimeckt** [comment]
Ich habe nun die 2.12.1 installiert und bekommen diese Meldung im Backend:

"You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product "

Der Lösungsansatz steht hier:

https://twittercommunity.com/t/forbidden-403-forbidden-453-you-currently-have-access-to-twitter-api-v2-endpoints-and-limited-v1-1-endpoints-only-but-i-pay-for-basic-plan/194460

**Comment by klimeckt** [comment]
Kurzes Update: Ich habe nun abraham/twitteroauth auf v2.x-dev aktualisiert. Damit kommt die Meldung "Social Feed: Twitter Import Account xxx" aber kein Import.

**Comment by seibtph** [comment]
Genauso ist es. Du benötigst mindestens die Basic-Variante für 100 USD/Monat, ansonsten kannst du keine Tweets mehr über die API abrufen. Siehe dazu folgender Tweet: https://twitter.com/TwitterDev/status/1621026986784337922.

Vielleicht ändert sich das irgendwann mal wieder, aber zur Zeit gibt es keinen anderen Weg.
