### ISSUE TITLE
Bildkomprimierung

### ISSUE THREAD

**Issue by snarosy75** [pdir/social-feed-bundle#114]
## Bug description
Die ins Nachrichtenarchiv importierten Bilddaten von Facebook sind sehr stark komprimiert. Das sieht dann Lässt sich dies ändern?
In der config.yml hätte ich einen Wert von jpeg_quality: 60 eingestellt, daran sollte es nicht liegen.
lg

**Comment by fritzmg** [comment]
> In der config.yml hätte ich einen Wert von jpeg_quality: 60 eingestellt

That's very low. Set it back to 90 or higher.
