### ISSUE TITLE
Feature: Pfad zum Stylesheet konfigurierbar machen

### ISSUE THREAD

**Issue by BennyK80** [pdir/social-feed-bundle#12]
Wäre es möglich, hier den den Pfad zu entfernen...

src/Resources/contao/config/config.php
`
if (TL_MODE == 'FE')
{
    $GLOBALS['TL_CSS'][] =  'bundles/pdirsocialfeed/css/social_feed.scss||static';
}`

... und dafür hier einzufügen?
src/Resources/contao/templates/modules/mod_newslist_social_feed.html5

` $GLOBALS['TL_CSS'][] =  'bundles/pdirsocialfeed/css/social_feed.scss||static';`

Vielen Dank im Vorraus

**Comment by seibtph** [comment]
In der Version 2.5.2 kann man den Pfad der Stylesheets einfach über das Template überschreiben.

`<?php  $GLOBALS['TL_CSS']['social_feed'] = 'bundles/pdirsocialfeed/css/social_feed.scss||static'; ?>`
