### ISSUE TITLE
FB Feed kann nicht abgerufen werden: "Facebook wird derzeit nicht unterstützt. Probiere Instagram aus."

### ISSUE THREAD

**Issue by w3scout** [pdir/social-feed-bundle#125]
Hallo,
wir nutzen Social Feed 2.12.3 in Contao 4.13, um damit die Posts einer Facebook-Seite zu importieren.
Die FB-App ist angelegt, die App-ID und die App Secret in der Konfiguration eingetragen. Die Verbindung zur FB-App und die Generierung eines Access-Tokens funktioniert einwandfrei.
Wenn man nun aber in das entsprechende News-Archiv geht und den Feed abrufen will, erscheint in Rot die Meldung "Facebook wird derzeit nicht unterstützt. Probiere Instagram aus."
Ist das Problem evtl. schon bekannt? Oder woran kann es liegen?
VG

**Comment by seibtph** [comment]
Der manuelle Import über das News-Archiv funktioniert derzeit nur für Instagram. Für die anderen Kanäle geht es nur über den Poor-Man-Cron von Contao. Stelle den Cronjob beim Social Feed Account z. B. auf stündlich und rufe dann die Webseite auf, dann sollten die Beiträge importiert werden (kann 1-2 Minuten dauern, bis sie zu sehen sind).

**Comment by w3scout** [comment]
Danke für das Feedback!
Der Import via Cronjob hat in dem Fall leider auch nicht funktioniert. Vermutlich, weil mein Kunde ein (noch) nicht verifiziertes Unternehmenskonto nutzt.
Ich kam dem ganzen leider erst auf die Schliche, nachdem ich mir die Fehlermeldungen des CronListener ins Contao Systemlog schreiben lies, da die Fehlermeldung sonst nirgends auftaucht.

Hab´ dazu vorhin einen PullRequest gemacht. Vielleicht habt´ Ihr ja Lust, den zu übernehmen?
VG
