### ISSUE TITLE
Kein Instagram Import

### ISSUE THREAD

**Issue by cheyenne25** [pdir/social-feed-bundle#13]
Leider funktioniert der Cronjob nicht, sodass keine Feeds geladen werden. Habe es auf zwei Webseiten probiert. Ich benutze Contao 4.4.

**Comment by seibtph** [comment]
Mit der Version 2.4.0 sollte der Fehler eigentlich behoben sein.

**Comment by cheyenne25** [comment]
Also ich habe die neueste Version 3.0.0 derzeit installiert.
