### ISSUE TITLE
Kein Instagram/Facebook Import

### ISSUE THREAD

**Issue by dchaot** [pdir/social-feed-bundle#14]
Instagram Import und Facebook Import funktioniert nicht. 

- Contao 4.4 LTS / Version 3.0 getestet und alternativ auch Version 2.4 - beide ohne Erfolg (hatte schon funktioniert, aber Testdaten (IG) wurden im Contao gelöscht für den echten Account).
- PHP 7.3 
- Testaccount (IG) hat eine eigene App, die mit anderen Modulen (cfg_instagram) auch problemlos funktioniert, aber hier ist ja nur der Nutzer erforderlich (mit anderen/bisherigem Nutzer kein Import mehr)
- für FB wurde vom Account-Inhaber eine App angelegt und App-ID, App-Key + Token übermittelt (kein Import)

Leider finde ich nichts in den Log-Dateien was mir weiter hilft. Vielleicht noch eine Idee? Oder ein Fehler?

**Comment by coolcontent** [comment]
Gleiches Problem hier mit Version 3 und Contao 4.8.7. Posts werden nicht importiert.

**Comment by MDevster** [comment]
Es gab leider einen kleinen Fehler bei der letzten Veröffentlichung. Könnt Ihr bitte eure Versionen auf ^2.4 umstellen, die aktuelle Version ist die 2.4.0! Bitte entschuldigt die Umstände.
