### ISSUE TITLE
Instagram Broken Image

### ISSUE THREAD

**Issue by samazaphikel** [pdir/social-feed-bundle#15]
Hallo,

an einigen Instagram Posts wird das Bild nicht korrekt Heruntergeladen. Im Post wird dann der Beitrag angezeigt ohne Bild, was natürlich optisch nicht sehr schön ist.

Wenn ich in den Nachrichten nun in Dateiverwaltung gehe und mir so ein Bild heraussuche, dann steht da **Broken Image**.

Geschätzt, würde ich sagen betrifft das ca. 15-20% der Beiträge.

![image](https://user-images.githubusercontent.com/35742942/76529109-1d5e7380-6472-11ea-89ca-829661239c55.png)

Kann man diese Bilder erneut herunterladen? Bzw. wie kann ich das verhindern?

**Comment by samazaphikel** [comment]
Schade, dass es nach 2 Wochen keinerlei Reaktion gibt. Somit leider ein unbrauchbares Plugin

**Comment by MDevster** [comment]
Bitte schick mal deinen Account den du importierst und deine Webseite wo die Beiträge eingebunden sind an support@pdir.de, dann schauen wir uns das Problem mal an.

**Comment by MDevster** [comment]
Vielleicht hilft es schon die betroffenen Beträge zu entfernen damit diese neu importiert werden.
