### ISSUE TITLE
Error: LinkedIn Access Token generation 

### ISSUE THREAD

**Issue by johannes-bittner** [pdir/social-feed-bundle#155]
## Bug description
Die (Re-)Generierung des Access Tokens für LinkedIn schlägt fehl mit der Fehlermeldung "json_decode(): Argument #1 ($json) must be of type string, bool given". 

## Steps to reproduce
Nach dem Markieren der Checkbox "Generiere Access Token" funktioniert die Weiterleitung zu LinkedIn, nach der Eingabe des Passworts und der Zurückleitung zu Contao erscheint dort aber die Fehlermeldung "json_decode(): Argument #1 ($json) must be of type string, bool given". 

## Screenshots

![grafik](https://github.com/user-attachments/assets/bd1c9cee-b2ed-4e19-a034-a6a97fbdcfe0)

## Bundle Version
Contao 4.13.49
social-feed-bundle 2.13.4

**Comment by MDevster** [comment]
Please check if the bug in 2.13.6 still exists. You are welcome to reopen the ticket at any time if the error still exists.

**Comment by johannes-bittner** [comment]
Works like a charm - thanks a lot!
