### ISSUE TITLE
CRITICAL Error InstagramScraper

### ISSUE THREAD

**Issue by Netzhirsch** [pdir/social-feed-bundle#16]
Hallo Zusammen,

wir erhalten auf einer etwas größeren Seite folgenden Fehler im Contao Log. Und das im Minutentakt.

https://pastebin.com/TvDvQpqr

Contao Version: 4.4.46
Social Feed Bundle: 2.4.0

**Comment by MDevster** [comment]
Wird ein Social Feed Instagram Account jede Minute abgefragt? Wird der Eintrag in der Log nicht mehr vorgenommen wenn der Social Feed Account deaktiviert wird?

Allgemeiner Hinweis für Instagram: Es ist zu empfehlen die Abfrage auf mind. 1 Stunde zu stellen da sonst sehr oft ein Abfragelimit von Instagram erreicht wird.

**Comment by MDevster** [comment]
Ich hab es selber noch nicht getestet, aber ich kann mir gut vorstellen das eine HTML Datei/Weiterleitung beim erreichen des Limits ausgeliefert wird, was den HTML Code beim API Abruf erklären würde. Ich werde mal versuchen das in der Entwicklungsumgebung nach zu stellen.

**Comment by Netzhirsch** [comment]
Ja, der Account wurde jede Minute abgefragt. Nun haben wir es auf eine Stunde gestellt und der Fehler tritt nicht mehr auf. Vielen Dank.

**Comment by MDevster** [comment]
Da werden wir den minütlichen Abgleich nur für Instagram mal entfernen :)
