### ISSUE TITLE
Style broken

### ISSUE THREAD

**Issue by soeren2k** [pdir/social-feed-bundle#17]
Since last update, the social stream is no more shown in columns. One news has the size of one whole row. Setting is ignored. Setting for "show pictures", "use masonary" etc is okay.

Same on my website (using excellent mate theme) and also on pdir mate demo site (on bottom): https://mate.pdir.de/.

**Comment by seibtph** [comment]
This bug is fixed in the MATE theme version 2.8.3. The bug only occurred if you used the MATE Theme with the Social Feed Bundle.

**Comment by klimeckt** [comment]
I have the same problem. The module is showing one column only. I use Rocksolid Oneo, Contao 4.9.3 with Social feed 2.5.0. If I change the number of columns, nothing changed on the frontend. 

`<div class="mod_newslist block">
<div class="social_feed_container">
<div class="social_feed_element extended arc_10 block first even" itemscope itemtype="http://schema.org/Article">
<div class="inner">
<div class="icon">`
