### ISSUE TITLE
Kein Import von Instagram

### ISSUE THREAD

**Issue by quintacom** [pdir/social-feed-bundle#19]
Nach Installation und Konfiguration dieser tollen Erweiterung kommen jedoch keine Inhalte von Instagram herein. Es wird zwar angezeigt, wann der letzte Import stattgefunden hat, aber es ist auf der Website nichts zu sehen. 
Über Facebook kommen die Daten dagegen problemlos rein. Ich hätte es, wegen der komplizierten Einrichtung mit der Facebook-App, eher anders herum erwartet. 

Woran kann das denn liegen. Außer der Angabe des Namen des Instagram-Accounts ist doch weiter nichts anzugeben.

**Comment by seibtph** [comment]
Ist bei _Ausführung des Cronjobs_ auch etwas ausgewählt? Ich habe es eben nochmal getestet und da hat der Import funktioniert.

**Comment by seibtph** [comment]
Es würde helfen, wenn der Cronjob mindestens stündlich ausgeführt wird. Ich konnte den Fehler jetzt ebenfalls nachstellen, wenn minütlich ausgewählt wird. Dann wird sehr oft ein Abfragelimit von Instagram erreicht. Nach Änderung des Cronjobs kann es einige Minuten dauern bis wieder importiert wird.

Wir werden in der nächsten Version dann das Feld minütlich deaktivieren, wenn Instagram ausgewählt wird.

**Comment by quintacom** [comment]
Hmm, das hilft bei mir alles nichts. :( 
Es war bereits auf stündlich eingestellt. Ich habe ben trotzdem noch einmal über Contao Manager 1.2.4 eine Aktualisierung vorgenommen und den Prod-Cache noch einmal gelöscht sowie anschließend eine komplette Systemwartung genmacht, Da wird nichts importiert. 

Mich wundert nur, dass für Facebook so ein Aufwand mit Facebook-App, Secret und Token gebraucht wird und für Instagram nur der Accountname einzutragen ist. Ist das so richtig oder fehlt da was in meiner Installation? Contao 4.4.48 läuft da.

**Comment by seibtph** [comment]
Für Instagram benötigt es nur den Accountnamen, da das über einen anderen Weg als bei Facebook ausgelesen wird.

Du kannst uns auch gern mal deinen Accountnamen bzw. einen Zugang zum Contao an support@pdir.de senden, wenn wir da mal drüberschauen sollen. Wir können auch mal versuchen den Account bei uns zu importieren.

**Comment by quintacom** [comment]
Ok, danke. Ich melde michgleich per E-Mail.

**Comment by MDevster** [comment]
fixed in version 2.6.0, but you need an app id and app secret for the instagram graph api
