### ISSUE TITLE
Facebook API V7.0 changed page permissions

### ISSUE THREAD

**Issue by rabauss** [pdir/social-feed-bundle#20]
I'm currently testing this extension for a new project. But unfortunately I saw a problem that I've already seen here: https://github.com/m-vo/contao-facebook-import/pull/26

Facebook has changed it's Page permission for the Graph API:

> On May 5, 2020, we released six new Page permissions to replace the manage_pages and publish_pages permissions. The manage_pages permission has been replaced with pages_manage_ads, pages_manage_metadata, pages_read_engagement, and pages_read_user_content. The publish_pages permission has been replaced with pages_manage_posts and pages_manage_engagement.

see: https://developers.facebook.com/docs/pages/managing/

If you generate a Token for V7.0 and use it in the social-feed-bundle, you will get the following error:
> This endpoint requires the 'manage_pages' or 'pages_read_engagement' permission or the 'Page Public Content Access' feature.

With a Token for V6.0 the import is (still) working

**Comment by baldur1989** [comment]
I have the same Problem

**Comment by seibtph** [comment]
With V7.0 you should add the following permissions:

- pages_show_list
- pages_read_user_content

Then it will works.

![facebook_token](https://user-images.githubusercontent.com/17127525/82469253-0ec0b800-9ac4-11ea-9a2e-640c4a64ae99.png)

**Comment by rabauss** [comment]
Oh nice, it's also in the docs: https://pdir.de/docs/de/contao/extensions/socialfeed/configuration/facebook/access-token/

By the way, in your docs on the contao landing page (https://pdir.de/docs/de/contao/) some extensions have the wrong link!
