### ISSUE TITLE
Facebook not supported

### ISSUE THREAD

**Issue by Midas1989** [pdir/social-feed-bundle#22]
Hallo,

ich habe die Erweiterung installiert und die Facebook App Daten angegeben.(inkl der restlichen Schritte laut Doku.

Ich bekomme unter "Nachrichten - MeinArchive - Social Feed - Feed abrufen" den Fehler 
Facebook is currently not supported.

3 Beiträge meiner Seite sind aber bereits sichtbar aber der Rest nicht.

**Comment by seibtph** [comment]
Das Moderation Feature (dass man bestimmte Posts zum Importieren auswählen kann) funktioniert bisher nur mit Instagram, die anderen Kanäle folgen noch.

Ansonsten kannst du aber einen Account anlegen und den Cronjob aktivieren, dann werden automatisch die Posts importiert.
