### ISSUE TITLE
The module is showing one column only

### ISSUE THREAD

**Issue by MDevster** [pdir/social-feed-bundle#23]
I have the same problem. The module is showing one column only. I use Rocksolid Oneo, Contao 4.9.3 with Social feed 2.5.0. If I change the number of columns, nothing changed on the frontend.

_Originally posted by @klimeckt in https://github.com/pdir/social-feed-bundle/issues/17#issuecomment-632580994_

**Comment by MDevster** [comment]
@klimeckt Sounds like a javascript error to me. Is there an error message in the developer console?

**Comment by klimeckt** [comment]
yes, getting errors like:
###
Die Ressource auf "https://www.google-analytics.com/analytics.js" wurde blockiert, weil das Blockieren von Seitenelementen aktiviert ist.
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. news.html
Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. jquery.min.js,contao-utils-bundle.js,netzhirschCookieOptIn.js,mo...-a99e4095.js:232:3946
trustedsite-tm-main[config][403] 1.js:46:136
trustedsite-tm-inline[config][403]
###

**Comment by MDevster** [comment]
Uhh... Do you have a link for me or a Contao admin account that we can check? You can send it to support@pdir.de.

**Comment by MDevster** [comment]
was a css problem (fixed - ticket system)
