### ISSUE TITLE
Kein Import und auch keinen Punkt Social Feed Einstellungen

### ISSUE THREAD

**Issue by derkosmonaut** [pdir/social-feed-bundle#27]
Moin,

wir haben das Plugin letzte Woche installiert und so weit auch eingerichtet. 
Contao 4.9.3
php 7.3

Bei uns erscheint im Backend unter dem Modul nicht der Punkt Social Feed Einstellungen. Auch findet kein Import von Facebook oder Instagram statt. Werden da nur die Sachen gezogen, die aktuell gepostet worden sind oder werden hier rückwirkend auch die Posts gezogen?

Bei FB gibt er folgende Fehlermeldung aus:  Facebook\\Exceptions\\FacebookAuthenticationException(code: 190): Error validating access token: Session has expired on Friday, 05-Jun-20 09:00:00 PDT. 
Wir haben da noch einmal die Einstellungen überprüft. Im Graph API Explorer wird uns unter Berechtigungen nicht die Möglichkeit "manage_pages" angezeigt. 

Viele Grüße aus Hamburg
Sebastian

**Comment by derkosmonaut** [comment]
Nach erneutem Anlegen einer Facebook-App bekommen wir jetzt noch zusätzlich folgenden Fehler:
Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT tl_news.* FROM tl_news WHERE tl_news.`social_feed_id`='XXXXXXXX'':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_news.social_feed_id' in 'where clause'" at 

Die Zeile fehlt tatsächlich. Wir haben nochmal den Cache geleert und das Installtool nochmal laufen lassen – die Zeile bleibt weg. Wir deinstallieren das Ganze mal und installieren neu....

**Comment by derkosmonaut** [comment]
Die Neu-Installation hat geholfen – Instagram klappt nicht, aber das haten ja auch schon andere angemerkt. :-)

**Comment by MDevster** [comment]
Bezüglich Instagram hier schauen #25
