### ISSUE TITLE
Contao Backend: jQuery is not defined

### ISSUE THREAD

**Issue by dive13** [pdir/social-feed-bundle#28]
Bei mehreren Projekten, wo ich das Plugin installiert habe, bekomme ich im Contao Backend einen JS-Error in der Konsole. Führt m. E. nach zu unerwartetem Verhalten des BE (Blätterfunktion gestört, Aktualisierung des Artikel- oder Seitenbaums gestört)

`Uncaught ReferenceError: jQuery is not defined at backend.js`

Verantwortlich dafür ist die /bundles/pdirsocialfeed/js/backend.js
Ganz wundert es mich nicht – das Contao BE verwendet doch gar kein jQuery, oder?

Plugin-Version: 2.5.1
Contao 4.9.3
php 7.3

**Comment by MDevster** [comment]
fixed in version 2.6.0
