### ISSUE TITLE
Scrape Error v 2.5.2 and Contao 4.9.3

### ISSUE THREAD

**Issue by rburch** [pdir/social-feed-bundle#29]
## Bug description
Using 2.5.2 and Contao 4.9.3

The scrape doesn't seem to working. It was but stopped when we upgraded about a month ago to Contao 4.9. 

The error in the login is huge, so here is the beginning and end of it:
request.CRITICAL: Uncaught PHP Exception InstagramScraper\Exception\InstagramException: "Response code is 200. Body: <!DOCTYPE html>...<body>  

Something went wrong. Please report issue. at /home/panpastel49bri/public_html/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:431)"} []

**Comment by MDevster** [comment]
fixed in version 2.6.0, but you need an app id and app secret for the instagram graph api
