### ISSUE TITLE
Nicht alle Bilder werden importiert

### ISSUE THREAD

**Issue by bixicy** [pdir/social-feed-bundle#31]
Hallo,
ich hatte nun etwas Zeit und habe das Plugin installiert und den Instagram Account dementsprechend eingerichtet. Es waren zwar nicht alle Bilder so wie in der Doku angegeben, aber am Ende hat es ja geklappt.

Es sit allerdings so, dass nicht alle Bilder von Instagram importiert werden. Bei einigen posts fehlen die Bilder.
Wenn ich im News Archiv auf **Social Feed** klicke und den feed abrufe, dann werden die Bilder in der Voransicht angezeigt. Beim importieren fehlen die Bilder dann allerdings. 
Wenn ich nun in den Beitrag hineingehe, dann ist bei **Ein Bild hinzufügen** der Haken nicht gesetzt.

Auch das löschen des Beitrages und neu importieren brachte hier keine Abhilfe, gibt es hierzu einen Tipp das zu beheben? Es sind leider der Überwiegende Teil bei denen die Bilder Fehlen.

In Dateiverwaltung fehlen die Bilder im übrigen genauso. Ich nutze die Version 2.7.0

**Comment by seibtph** [comment]
Hallo @bixicy,

könntest du bitte mal Version 2.7.1 testen ob das Problem nun gelöst ist?

Der Fehler scheint bei Beiträgen mit mehreren Bildern aufzutreten und auch nur, wenn man die Beiträge manuell im News-Archiv importiert?

**Comment by bixicy** [comment]
Hi,

ich habe auf 2.7.1 aktualisiert und die Fehlerhaften feeds gelöscht. Jetzt konnte ich fehlerfrei manuell importieren.

Gestern ging das mit dem pseudo Cronjob auch nicht zu importieren, da fehlten dann auch die Bilder. Ja, wir haben fast immer mehr wie nur 1 Bild, evtl. lag es daran.

Danke für die schnelle Hilfe
