### ISSUE TITLE
Instagram Access Token anfordern -> "Invalid scope" 

### ISSUE THREAD

**Issue by Schooott** [pdir/social-feed-bundle#32]
Wir haben einen Instagram Feed wie in der Dokumentation beschrieben eingerichtet. Beim Anfordern des Access Token bekommen wir allerdings folgende Fehlermeldung. Dazu konnten wir in der Doku nichts finden.

`{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: []"}`

Social Feed 2.7.0
Contao 4.8.8

**Comment by bixicy** [comment]
Hi,
das hatte ich auch...
Falsche ID kopiert.

Die unter ID und Token kopieren und nicht die in der Kopfzeile
![image](https://user-images.githubusercontent.com/46830537/88595456-40757280-d063-11ea-9e5e-f6461c447bec.png)

**Comment by Schooott** [comment]
Leider nicht, wir bekommen den Fehler mit der korrekten ID und Secret. :(

**Comment by seibtph** [comment]
Ich hab es eben nochmal mit der aktuellen Version getestet und habe es zum Laufen gebracht.

Hast du wirklich alle Schritte aus der Doku so befolgt?
- Sind alle URLs eingetragen?
- Ist ein Instagram Tester angelegt und die Einladung akzeptiert worden? Ich glaube der Account benötigt auch Zugang zu der Seite, die ausgelesen werden soll.

**Comment by Schooott** [comment]
Danke für die Hinweise. Mittlerweile sind wir ein bisschen weiter. Wir kommen zur Authentifizierung bei Instagram und bekommen über die URL wohl auch einen korrekten Token zurück.

https://domain.de/_instagram/auth?code=XXXXXXXXXXXXXXX

Allerdings jetzt mit dem Fehler "Bad Request".

**Comment by seibtph** [comment]
@Schooott Was ist in den Feldern **Client-OAuth-Einstellungen**, **Autorisierung widerrufen** und **Anfragen zur Löschung von Daten** für eine URL eingetragen? Die Domain sollte die gleiche sein wo der Feed angezeigt wird.

**Comment by Schooott** [comment]
Jeweils überall die gleiche mit /_instagram/auth. Das ist auch die Seite auf welcher der Feed angezeigt werden soll.

![instagramoauth](https://user-images.githubusercontent.com/1781223/90602982-d59aff80-e1fa-11ea-92b4-7595e00af447.png)

**Comment by seibtph** [comment]
Das sollte passen. Ein Tester ist auch angelegt und dessen Einladung auch akzeptiert worden? Die Fehlermeldung kommt beim Erstellen des Access Token im Contao Backend?

**Comment by Schooott** [comment]
Ja, der Instagram Account der später angezeigt werden soll ist als Tester angelegt und die Einladung wurde akzeptiert. Beim speichern und generieren des Access Token im Feed sind wir auch parallel im Instagram Account eingeloggt und die Authentifizierungsanfrage von Instagram erscheint korrekt. Nach der Genehmigung kommt dann nur "Bad request" als Fehler.

**Comment by seibtph** [comment]
Man kann in der App unter User Token Generator (dort wo der Tester angezeigt wird) auch einen Token generieren. Funktioniert das? Wenn da ein Token generiert wird, könnte man den auch in der Datenbank setzen (Tabelle tl_social_feed), dann müsste es auch funktionieren.

**Comment by netgroupgmbh** [comment]
> 
> 
> Man kann in der App unter User Token Generator (dort wo der Tester angezeigt wird) auch einen Token generieren. Funktioniert das? Wenn da ein Token generiert wird, könnte man den auch in der Datenbank setzen (Tabelle tl_social_feed), dann müsste es auch funktionieren.

Bei mir hat es damit geklappt. Danke!

**Comment by Schooott** [comment]
> Man kann in der App unter User Token Generator (dort wo der Tester angezeigt wird) auch einen Token generieren. Funktioniert das? Wenn da ein Token generiert wird, könnte man den auch in der Datenbank setzen (Tabelle tl_social_feed), dann müsste es auch funktionieren.

Das hat geklappt, danke für den Tipp. 👍

**Comment by seibtph** [comment]
Super! :) Wir werden das Access Token Feld im Backend im nächsten Update wieder editierbar machen und in der Doku erklären, dass man den Token auch in der App generieren kann, wenn der andere Weg nicht funktioniert.
