### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by christianbargon** [pdir/social-feed-bundle#33]
<img width="2213" alt="Bildschirmfoto 2020-08-03 um 15 58 13" src="https://user-images.githubusercontent.com/29036607/89190795-465ade80-d5a2-11ea-8bdf-7d7ae65ef1b3.png">

Leider kommen wir hier nicht weiter - Haben versucht einen Facebook-Account zu verknüpfen. Der Fehler kommt wenn ich unter Nachrichten versuche den Feed zu laden - Punkt: Feed abrufen.

Gruß Chris

**Comment by christianbargon** [comment]
Version Contao 4.9.3 - Extension Version: 2.7.0.

**Comment by MDevster** [comment]
Hey Christian, kannst du mir mal an support@pdir.de einen Contao Zugang und FTP/SSH Daten schicken, dann schauen wir mal was das Problem ist. Gern https://secure.pdir.de verwenden.

**Comment by christianbargon** [comment]
Hi Matthias,

vielen lieben dank für die schnelle Rückmeldung – Habe dir über secure.pdir.de die Daten geschickt.

Ich tippe darauf, dass irgendwas nicht mit dem Api-Keys/Tokens ect. Stimmt. Bekomme aber auch keine sonstige Fehlerausgabe.

Mit freundlichen Grüßen

CHRISTIAN BARGON

[emailfooter]

adress  Reisertstr. 28 • 53773 Hennef
tel         +49 (0) 22 42 - 91 71 6-10
fax        +49 (0) 22 42 – 91 71 6-19
mobil    +49 (0) 171 655 78 60
mail      chris@christianbargon.de<mailto:chris@christianbargon.de>
web      http://www.christianbargon.de<http://www.christianbargon.de/>

Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich erhalten haben, informieren Sie bitte sofort den Absender und loeschen Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient, or, if you have received this e-mail in error, please notify the sender immediately and destroy this e-mail. Any nauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden!


Von: Mathias Arzberger <notifications@github.com>
Antworten an: pdir/social-feed-bundle <reply@reply.github.com>
Datum: Montag, 3. August 2020 um 17:39
An: pdir/social-feed-bundle <social-feed-bundle@noreply.github.com>
Cc: Christian Bargon <info@christianbargon.de>, Author <author@noreply.github.com>
Betreff: Re: [pdir/social-feed-bundle] Warning: Invalid argument supplied for foreach() (#33)


Hey Christian, kannst du mir mal an support@pdir.de<mailto:support@pdir.de> einen Contao Zugang und FTP/SSH Daten schicken, dann schauen wir mal was das Problem ist. Gern https://secure.pdir.de verwenden.

**Comment by seibtph** [comment]
@christianbargon Ich habe dir per Mail geantwortet. Daher schließe ich das Ticket hiermal.

**Comment by christianbargon** [comment]
Hi Philipp,

ich habe sonst keine Email von dir – auch nicht im Spam – kannst du mir deine Antwort nochmal kurz weiterleiten?

Die Info, dass du das Ticket geschlossen hast habe ich bekommen (über Github) und deine Email, dass du das Ticket schließt…


Mit freundlichen Grüßen

CHRISTIAN BARGON

[emailfooter]

adress  Reisertstr. 28 • 53773 Hennef
tel         +49 (0) 22 42 - 91 71 6-10
fax        +49 (0) 22 42 – 91 71 6-19
mobil    +49 (0) 171 655 78 60
mail      chris@christianbargon.de<mailto:chris@christianbargon.de>
web      http://www.christianbargon.de<http://www.christianbargon.de/>

Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich erhalten haben, informieren Sie bitte sofort den Absender und loeschen Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient, or, if you have received this e-mail in error, please notify the sender immediately and destroy this e-mail. Any nauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden!


Von: Philipp Seibt <notifications@github.com>
Antworten an: pdir/social-feed-bundle <reply@reply.github.com>
Datum: Donnerstag, 13. August 2020 um 17:34
An: pdir/social-feed-bundle <social-feed-bundle@noreply.github.com>
Cc: Christian Bargon <info@christianbargon.de>, Mention <mention@noreply.github.com>
Betreff: Re: [pdir/social-feed-bundle] Warning: Invalid argument supplied for foreach() (#33)


@christianbargon<https://github.com/christianbargon> Ich habe dir per Mail geantwortet. Daher schließe ich das Ticket hiermal.

**Comment by seibtph** [comment]
Hallo Christian,

ich habe dir die Mail jetzt nochmal weitergeleitet. Ich hoffe sie ist diesmal angekommen.

**Comment by Falkgeist** [comment]
Habe das gleiche Problem, was war hier die Ursache und dann die Lösung?
