### ISSUE TITLE
Stylesheet Warnung/Fehler in Konsole

### ISSUE THREAD

**Issue by sfx12** [pdir/social-feed-bundle#34]
Folgende Fehlermeldung im Firefox & Chrome

Stylesheet https://www.meinedomain.de/bundles/pdirsocialfeed/css/social_feed.scss wurde nicht geladen, weil sein MIME-Typ, "text/plain", nicht "text/css" ist.

## Bundle Version
SocialFeedBundle (Version: 2.5.2)

##weitere Info
Contao 4.93 - php 7.2

**Comment by seibtph** [comment]
Müsste eigentlich schon behoben sein. Mal bitte mit der neuesten Version (2.8.0) testen.

**Comment by sfx12** [comment]
Das Problem besteht dennoch, auch mit Version 2.8.0 :-(

hier der link: [www.mobil-world.de](url)

**Comment by seibtph** [comment]
@sfx12 Hast du einen Link zur Seite? Dein Link funktioniert leider nicht. Du kannst uns auch gern mal einen Contao-Admin-Zugang an support@pdir.de senden, wenn wir da mal hineinschauen sollten. Leider konnte ich den Fehler noch nicht finden, in unserer Demo funktioniert es mit der aktuellen Version.

**Comment by sfx12** [comment]
Hallo, du musst den link kopieren und im Browser einfügen, ich sende dir jedoch mal die Zugangsdaten per email.. Vielen Dank schonmal.
