### ISSUE TITLE
Problem mit verknüpftem Facebook bzw. Instagram Account

### ISSUE THREAD

**Issue by MrFastcats** [pdir/social-feed-bundle#35]
Guten Tag, 

ich möchte auf meiner Seite einen Instagram Social Feed einbinden. Wie in der [Anleitung beschrieben](https://pdir.de/docs/de/contao/extensions/socialfeed/configuration/instagram/) habe ich mich für den Facebook Developers Bereich mit meinem Facebook Konto angemeldet (die eigentliche Seite, die im Feed angezeigt werden soll ist mit meinem Account verknüpft). Jedoch kann ich für die "Instagram Basic Display App" nur meinen privaten Facebook bzw. Instagram Account auswählen, jedoch nicht den Account der Facebook-Seite, die mit der App verknüpft werden soll. 

Wie schaffe ich es, die "Instagram Basic Display App" für die gewünschte Facebook-Seite anzulegen? 

Danke und viele Grüße!

**Comment by seibtph** [comment]
Ich versteh noch nicht ganz was das Problem ist. Hast du einen Instagram-Tester angelegt? Am besten den Account, der ausgelesen werden soll. Und anschließend die Einladung bei instagram.com akzeptieren. Auf jeden Fall brauchst du Zugriff zu der Instagram-Seite, die ausgelesen werden soll.

**Comment by MrFastcats** [comment]
Hallo, 
ich bin mit meinem privaten FB-Konto als Admin für die Facebook bzw. Instagram Seite unseres Vereins angelegt. Den Vereins-Instagram-Account konnte ich zwischenzeitlich als "Tester" in der App hinterlegen. Ist es für die Nutzung des Feeds zwingend erforderlich, sich für den Facebook Business Manager anzumelden und sein "Unternehmen" verifizieren zu lassen?

**Comment by seibtph** [comment]
Sollte nicht nötig sein. Wenn du den Access Token im Contao Backend generierst, sollte der Instagram Feed funktionieren.

**Comment by MrFastcats** [comment]
Danke für die schnelle Antwort. Letzte Frage: Wie kann die Länge der einzelnen Posts im Feed (siehe Screenshot) nach unten auf eine einheitliche Länge beschränkt werden?
<img width="1210" alt="Bildschirmfoto 2020-08-13 um 12 34 00" src="https://user-images.githubusercontent.com/69518986/90126700-60e04500-dd64-11ea-88c7-72ab6d5dbeff.png">

P.S. Wird in einer zukünftigen Version die Hervorhebung der Hashtags unterstützt?

**Comment by seibtph** [comment]
Du kannst in den Einstellungen des Moduls der Nachrichtenliste Masonry deaktivieren. Und durch folgende CSS-Anweisung kannst du alle Beiträge auf die gleiche Höhe bringen:

```
.social_feed_element .inner {
    height: 100%;
}
```

Die Hervorhebung der Hashtags bei Instagram könnten wir zukünftig mal integrieren, wir haben uns das mal vorgemerkt.
