### ISSUE TITLE
Instagram Import only 25 Posts

### ISSUE THREAD

**Issue by SGehle** [pdir/social-feed-bundle#37]
## Bug description
Only 25 Instagram Posts will be imported

## Steps to reproduce
Import from certain Instagram Page with more than 25 Posts

## Expected behavior
I would like to import all Posts, not only 25.
## Bundle Version
2.8.1

## Environment
Contao 4.9

**Comment by SGehle** [comment]
This happens because of the Instagram Graph API Pagination

**Comment by SGehle** [comment]
See #38

**Comment by MDevster** [comment]
fixed in version 2.8.2
