### ISSUE TITLE
Instagram/Facebook Likes & comments ?

### ISSUE THREAD

**Issue by sfx12** [pdir/social-feed-bundle#40]
Hallo,

es wäre schön das man aus insta & facebook auch die likes eines Beitrags mit angezeigt bekommt, wäre doch kein großer Aufwand !?

PS: Danke für die tolle extension!

**Comment by seibtph** [comment]
Das wäre ein schönes Feature, aber ich weiß noch nicht so recht ob das Sinn macht das mit zu importieren. Man müsste dann ja regelmäßig nach Kommentaren und Likes schauen und diese importieren. Es reicht ja nicht aus diese beim ersten Auslesen, wenn die News angelegt wird, zu importieren. Wenn der Beitrag da noch sehr jung ist werden es nicht sehr viele Likes/Kommentare sein.

**Comment by Total-Reality** [comment]
Ich kann mir zum einen nicht vorstellen, dass das einfach umzusetzen ist. Zum zweiten wird Instagram das mit Sicherheit nicht unterstützen und zu guter letzt wäre das ein riesen Datenschutz-Leck und ist mit Bestimmtheit nicht DSGVO konform. 
Abgesehen davon wer braucht sowas? Ich kenne sonst niemanden.
Wer die Kommentare lesen will, kann doch einfach auf "Mehr lesen" klicken.

Ggf. ergibt es noch Sinn die Anzahl der Kommentare zu importieren, aber dann müsste die Erweiterung wirklich ständig auf jeden Beitrag gucken, ob es dort neue Kommentare gibt...
Also alles in allem kein wirklich sinnvolles und realitätsfernes Feature.
