### ISSUE TITLE
double entries

### ISSUE THREAD

**Issue by stone2k2aut** [pdir/social-feed-bundle#41]
from time to time some entries appear 2 times in the news archive. any ideas how to solve this ?

**Comment by Total-Reality** [comment]
I can confirm this, but it is seldom

**Comment by MDevster** [comment]
@stone2k2aut @Total-Reality for all accounts (instagram, facebook and twitter) or a single?

**Comment by Total-Reality** [comment]
> @stone2k2aut @Total-Reality for all accounts (instagram, facebook and twitter) or a single?

I never saw it in instagram archives. Only one time or two times in a twitter archive

**Comment by seibtph** [comment]
@stone2k2aut @Total-Reality Has the error occurred again in the meantime? I don't noticed this error in the last time.

**Comment by stone2k2aut** [comment]
Hello, so far all is working fine till today. we have also updated to latest version. thank you for your effort. in case it happens again i let u know.
