### ISSUE TITLE
Facebook wird nicht aktualisiert

### ISSUE THREAD

**Issue by hllrsa** [pdir/social-feed-bundle#42]
Woran liegt es, dass Facebook Einträge nicht mehr aktualisiert werden? Mein letzter eingefügter Post war von Anfang November, seither wurden keine neuen hinzugefügt... Ich habe auch den Token schon verlängert, funktioniert aber trotzdem nicht.

**Comment by MDevster** [comment]
Das Verhalten müssen wir erst genauer untersuchen. Bei einigen Benutzern hat es geholfen sich mit dem Entwicklerkonto regelmäßig anzumelden. Wir prüfen ob wir hier etwas automatisieren können um das Konto "aktiv" zu halten.

**Comment by MDevster** [comment]
Doppelter Eintrag https://github.com/pdir/social-feed-bundle/issues/39
