### ISSUE TITLE
Twitter - Kaputte/leere Bilder werden importiert und führen zum Absturz der kompletten Website

### ISSUE THREAD

**Issue by Total-Reality** [pdir/social-feed-bundle#43]
## Bug Beschreibung
Die Bilder von einigen Beiträgen aus Twitter werden scheinbar nicht korrekt geladen und sind dann in der Dateiverwaltung 0 Byte groß. Die Bilder werden dennoch zum Beitrag zugeordnet (singleSRC und addImage in der Tabelle tl_news). Das führt dazu, dass die komplette Seite im Frontend abstürzt (sofern man sich auf der Seite befindet wo die Newsliste mit den Beiträgen von Twitter ist).

Es ist übrigens nicht immer das gleiche Bild betroffen. Wenn man z.B. 5 Beiträge importiert, dann sind 3 davon kaput. Wenn man danach die Beiträge und Bilder löscht, dann werden beim erneuten Import 2 bis 4 andere Bilder kaputt importiert.

## Mögliche Ursache des Problems

Entscheidend ist hier denke ich Zeile 365 bis 370 in dieser Datei:
https://github.com/pdir/social-feed-bundle/blob/master/src/EventListener/CronListener.php#L365

Eine Abfrage, ob $strImage  existiert, wäre denke ich zielführend. Also $file->write soll nur dann ausgeführt werden...
Das würde sicherlich dazu führen, dass keine leeren Daten als Bild importiert werden. Daraus folgend sollte dann natürlich auch nur eine Bildzuordnung (singleSRC + addImage) erfolgen, sofern $strImage existiert...
Das löst zwar nicht das Problem an sich, aber es verhindert die Folgen - nämlich der dramatische Absturz der gesamten Website.

## Version
Die neueste Version der Erweiterung ist installiert unter Contao 4.4. 
PHP 7.2 ist installiert.

**Comment by seibtph** [comment]
@Total-Reality Tritt das Problem aktuell immer noch auf? Vielleicht kannst uns mal per E-Mail (support@pdir.de) API Key, Secret Key, Token und Token Secret von dem Account, den es betrifft, senden? Ich konnte den Fehler bisher noch nicht reproduzieren.

**Comment by Total-Reality** [comment]
> @Total-Reality Tritt das Problem aktuell immer noch auf? Vielleicht kannst uns mal per E-Mail ([support@pdir.de](mailto:support@pdir.de)) API Key, Secret Key, Token und Token Secret von dem Account, den es betrifft, senden? Ich konnte den Fehler bisher noch nicht reproduzieren.

Wir haben jetzt auf die aktuellste Contao 4.4 Version aktualisiert, also 4.4.55 und Social Feeds Version 2.8.4.
Die Bilder der Beiträge sind jetzt da und nicht mehr kaputt. 
Problem scheint gelöst worden zu sein.
