### ISSUE TITLE
Masonry doesn't work

### ISSUE THREAD

**Issue by ncwerbung** [pdir/social-feed-bundle#45]
unfortunately the arrangement does not work.

**Comment by seibtph** [comment]
Have you more details? Which contao and social feed version do you use? Maybe you have a link to your page?

**Comment by ncwerbung** [comment]
Link: https://facelift.das-katschberg.at/social-feed.html

Contao: 4.9.8 / Social Feed 2.8.3

thanks

**Comment by seibtph** [comment]
The link is not avalaible. But I think this is not a bug from the social feed. I have installed contao 4.9 and social feed 2.8.4 and it works.

Feel free to reopen the ticket if the problem still occurs.
