### ISSUE TITLE
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0 ...' for column 'headline' at row 1

### ISSUE THREAD

**Issue by MinSukOh-boldventures** [pdir/social-feed-bundle#46]
## Bug description
For a Customer we used the pdir/social-feed-bundle and following we had following issues for post which starts with multiple in the first line. 

```
'INSERT INTO tl_news (`pid`, `social_feed_type`, `social_feed_id`, `social_feed_config`, `addImage`, `singleSRC`, `headline`, `teaser`, `date`, `time`, `published`, `source`, `target`, `url`, `tstamp`) VALUES (..........)': SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0 ...' for column 'headline' at row 1
``` 

We figured out, that the customer usually starts his post with 6 country emojis in the first line. 
Other Posts where imported mostly correctly.

The social-feed-bundle tries to divides the post-message (`$message`) into[ `$headline`](https://github.com/pdir/social-feed-bundle/blob/master/src/Importer/NewsImporter.php#L67)  and [`$teaser`](https://github.com/pdir/social-feed-bundle/blob/master/src/Importer/NewsImporter.php#L76).

```
// .../vendor/pdir/social-feed-bundle/src/Importer/NewsImporter.php

...
$more = '...';
...

$objNews->headline = substr($message, 0, 50) . $more;
```

First I tried to  import the post directly to the database to figure out the issue:
Even if the `INSERT` statement works, it has the side-effect, that the title in the backend will just contain `...`, and I had all entries titled with `...` (which makes sense, because the first line just contains emojis), which makes the posts very difficult to differentiate the posts.
.

## Hotfix
To  fix those two issues, I implemented a hot-fix to remove the emojis from the headline in the Importer and Cron script.
```
// .../vendor/pdir/social-feed-bundle/src/Importer/NewsImporter.php
// .../vendor/pdir/social-feed-bundle/src/EventListener/CronListener.php

// $objNews->headline = substr($message, 0, 50) . $more;
// strip everything except basic printable ASCII characters
$objNews->headline = substr(preg_replace('/[[:^print:]]/', '', $message), 0, 50) . $more;
```
Now the headline just contains printable text. 
I don't know if this fix will have a bad side-effect on other languages... (The customer is using german, english, italian, french)

I hope this issue will be fixed soon to keep that bundle upgrade-able.

## Bundle Version
Version 2.8.3

## Environment
Contao Version 4.9.10

**Comment by MinSukOh-boldventures** [comment]
This might be the attempt to fix this issue, but it does not contain all emojis?

https://github.com/pdir/social-feed-bundle/blob/master/src/Importer/NewsImporter.php#L95

**Comment by MDevster** [comment]
Please check your database encoding. You could set the encoding to utf8mb4 and the collation to utf8mb4_generic_cl and everithing works fine ;) In newer contao isntallation is it standard.
