### ISSUE TITLE
Instagram-Bilder werden nicht gezeigt

### ISSUE THREAD

**Issue by jankout** [pdir/social-feed-bundle#47]
Die Bilder von Instagrambeiträgen werden nicht gezeigt.

## Bundle Version
<img width="875" alt="Screenshot_Instagram_2" src="https://user-images.githubusercontent.com/3715050/103706783-b801e300-4fad-11eb-9439-0d3c37d71da3.png">
<img width="1063" alt="Screenshot_Instagram_1" src="https://user-images.githubusercontent.com/3715050/103706798-be905a80-4fad-11eb-8117-6ae68969f6ac.png">

die letzte Version

## Environment
Contao 4.10.5

**Comment by seibtph** [comment]
Den Fehler kann ich leider nicht reproduzieren. Ich habe es mal der neuesten Version getestet und da hat alles geklappt. Du könntest uns z. B. mal die APP ID, App Secret und den Access Token per Mail (support@pdir.de) senden, damit wir das mal bei uns probieren können zu importieren. Oder uns Zugangsdaten zum Contao zukommen lassen.

Der Ordner social-feed ist auch öffentlich?

**Comment by jankout** [comment]
Hallo, wir können diese Ticket schließen, weil es nächsten Tag da doch war. Vielen Dank für die schnelle Reaktion
