### ISSUE TITLE
Facebook: Immer wieder "Error validating access token: The session is invalid because the user logged out."

### ISSUE THREAD

**Issue by fitzworld** [pdir/social-feed-bundle#48]
Wir erhalten immer wieder die folgende Fehlermeldung beim Facebook-API-Zugriff:
**Error validating access token: The session is invalid because the user logged out. at /data/xxx/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:89)"} []**

Bei Eingabe eines neuen Access Tokens funktioniert dieser wieder kurzzeitig, dann erscheint wieder o.g. Meldung im Log.

Plugin ist im Einsatz mit Contao 4.10 unter PHP 7.4.

Kann das am Plugin liegen? 
Danke für Feedback!

**Comment by MDevster** [comment]
Please test the new "generate facebook access token via checkbox" feature in version 2.9.0 in back end.
