### ISSUE TITLE
Facebook: Bilder/Bild-URL scheinen nicht mit importiert zu werden

### ISSUE THREAD

**Issue by b3acon** [pdir/social-feed-bundle#50]
Bilder/Bild-URL scheinen nicht mit importiert zu werden.
Es wäre super wenn man hier nachbessern würde.

**Comment by seibtph** [comment]
Welche Contao-Version und Social Feed Version nutzt du denn? Falls es neuere Versionen gibt, würde ich erstmal versuchen upzudaten.

Ich konnte den Fehler in unserer Testumgebung nicht nachstellen. Normalerweise sollten die Bilder in der Dateiverwaltung unter social-feed angelegt werden, sind diese denn da?

Gern kannst du uns ansonsten einen Contao Admin-Zugang zusenden, wenn wir mal hineinschauen sollen (per E-Mail an support@pdir.de).

**Comment by MDevster** [comment]
I'm closing the ticket because there was no response. You are welcome to reopen the ticket if your problem is not solved.
