### ISSUE TITLE
Facebook: Dokumentation veraltet. (Bereich Konfiguration)

### ISSUE THREAD

**Issue by b3acon** [pdir/social-feed-bundle#51]
Facebook hat den Dev-Modus abgeschafft. Der heißt wohl nun TestAPP. Muss anders angelegt werden.

_Die App muss im Dev-Modus laufen und darf nicht live geschaltet werden._

Dieser Part in der Doku müsste geändert werden.

**Comment by MDevster** [comment]
Documentation was updated.
https://pdir.de/docs/de/contao/extensions/socialfeed/configuration/facebook/
