### ISSUE TITLE
Instagram Feed Import keine Vorschaubilder ?

### ISSUE THREAD

**Issue by sfx12** [pdir/social-feed-bundle#52]
## Bug description
Keine Vorschaubilder beim Feed Import

## Screenshots
[](url)
![image](https://user-images.githubusercontent.com/16244014/108342051-a467b000-71da-11eb-8b6b-89520f835a14.png)

## Bundle Version
SocialFeedBundle (Version: 2.8.4)

## Environment
Contao 4.9.10 - PHP 7.4

**Comment by seibtph** [comment]
Hallo @sfx12,

wäre es möglich einen Link zur Seite und vielleicht sogar einen Contao Zugang zu bekommen (gern per E-Mail an support@pdir.de)?

Der Fehler ist mir jetzt nicht bekannt. Normalerweise werden die Bilder in der Dateiverwaltung unter social-feed angelegt. Sind die Bilder denn vorhanden? Ist der Ordner öffentlich?

**Comment by MDevster** [comment]
I'm closing the ticket because there was no response. You are welcome to reopen the ticket if your problem is not solved.
