### ISSUE TITLE
Feed Import "Zahlauswahl"

### ISSUE THREAD

**Issue by sfx12** [pdir/social-feed-bundle#53]
## Description
Es wäre gut wenn man beim Import z.b. "ältestes Datum" oder eine maximal Anzahl des Abrufs wählen könnte, wie z.B. "rufe ab frühestes Datum xx.y ab oder rufe die letzen 20/30/50 postings ab, wenn jemand doch so an die 1000 Beiträge hat und ich rufe den Feed ab, geht der Browser doch ziemlich in die Knie!

**Comment by MDevster** [comment]
Added in version 2.9.0. You can now limit the number of posts.
