### ISSUE TITLE
Twitter - "Leere" Beiträge werden importiert - Text und Titel sind leer

### ISSUE THREAD

**Issue by Total-Reality** [pdir/social-feed-bundle#54]
## Bug Beschreibung
Es werden Beiträge aus Twitter importiert, die keinen Titel und keinen Teasertext haben. Die Beiträge haben nur Datum und Uhrzeit.
Im Backend in der Liste steht dann z.B. einfach nur [26.02.2021 09:53]
Beim Bearbeiten sieht man dann ja die Social Feed ID, also konnte ich herausfinden um welchen Beitrag es sich handelt.

Zum Beispiel wurde folgender Beitrag nicht korrekt importiert:
https://twitter.com/IMG_ST/status/1365223347651543042

Dieser ist ebenfalls nicht korrekt übernommen worden:
https://twitter.com/IMG_ST/status/1364499529219866624

Dieser Beitrag dagegen wird ganz normal gezogen und alles ist korrekt:
https://twitter.com/IMG_ST/status/1369245462289657860

Nachdem ich alle Beiträge in Contao gelöscht habe und den Import erneut laufen gelassen habe, ist das gleiche Problem wieder aufgetreten... immer die gleichen Beiträge bleiben leer.
Das scheint nicht mit allen Twitter-Accounts zu passieren, bei Spiegel Online z.B. tritt das nicht auf.

Wir haben eingestellt bei der Social Feed Konfiguration - Twitter Account: IMG_ST
Maximale Anzahl an Post: 20

## Mögliche Ursache des Problems
Ich vermute, dass die Ursache ist, dass die ihre problematischen Beiträge mit einem Icon beginnen.

## Version
Die neueste Version der Erweiterung ist installiert unter Contao 4.4.55
PHP 7.2 ist installiert.

**Comment by MDevster** [comment]
Please check your tl_news table. Maybe changing charset to utf8mb4 and collation to utf8mb4_unicode_ci will help.
