### ISSUE TITLE
Verlinkung für Tweets mit enthaltener URL ist fehlerhaft

### ISSUE THREAD

**Issue by frederikmoellers** [pdir/social-feed-bundle#57]
## Bug Beschreibung
Bei Twitter-Posts wird eine verlinkte URL als URL für den gesamten Beitrag hinterlegt. Eventuelle Bilder sowie der "Weiterlesen" Button verweisen dann auf diese URL, anstatt auf die URL zum Tweet selbst.

## Reproduktion
1. Twitter-Account einbinden
2. Tweet mit einer URL (und optional einem Bild) absetzen
3. Diesen Tweet per social-feed auf der Webseite anzeigen lassen

## Erwartetes Verhalten
Der "Weiterlesen"-Button sowie das Bild verweisen auf die URL des Tweets (https://twitter.com/accountname/status/tweet-id)

## Bundle Version
2.8.5

## Umgebung
Contao 4.9.13, PHP 7.4

**Comment by seibtph** [comment]
fixed in version 2.9.0

**Comment by frederikmoellers** [comment]
Perfect, thank you! ♥️
