### ISSUE TITLE
Sporadischer Contao Fehler durch Import

### ISSUE THREAD

**Issue by FlowinBeatz** [pdir/social-feed-bundle#58]
## Bug description
Ich erhalte sowohl im Frontend (ohne Fehlermeldung) als auch im Backend (mit Fehlermeldung) einen Contao-Fehler. Ich vermute sehr stark dass er durch den Import und Emojis ausgelöst wird.

## Steps to reproduce
Nachrichten vom Twitter-Account peppermint_vp importieren. Fehler tritt dann im Intervall des Cronjobs auf.

## Expected behavior
Keine Fehlermeldung und erfolgreicher Import der Tweets.

## Screenshots
![Bildschirmfoto 2021-05-18 um 10 19 19](https://user-images.githubusercontent.com/4570808/118619001-7b988c00-b7c4-11eb-8ac7-e2aca01f139f.png)

## Bundle Version
2.8

## Environment
PHP 7.4.2
Contao 4.9.13

**Comment by seibtph** [comment]
Hast du es mal mit der Version 2.8.5 probiert, ob dort der Fehler immer noch auftritt? Ich konnte den Fehler in unserer Testumgebung nicht reproduzieren, da wurde alles korrekt importiert. Tritt der Fehler regelmäßig auf oder nur manchmal?

**Comment by MDevster** [comment]
@FlowinBeatz Please check your tl_news table. Maybe changing charset to utf8mb4 and collation to utf8mb4_unicode_ci will help.

**Comment by MDevster** [comment]
@FlowinBeatz Feel free to reopen the ticket if your issue is not resolved.
