### ISSUE TITLE
Facebook-Import: No news imported

### ISSUE THREAD

**Issue by cmartin6** [pdir/social-feed-bundle#64]
## Bug description
I added a facebook-account as mentioned in the documentation, but no news are imported - I generated a access token and the fields concerning the last import-infos are filled...

## Bundle Version
Version 2.9.0

## Environment
Contao 4.9.16

**Comment by proplab** [comment]
Exactly the same here but instagram. Version 2.9.0 (since update from 2.8.5), Contao 4.9.16

**Comment by MDevster** [comment]
Are you using a new account or an existing one and after the update the import doesn't work anymore? We have updated the documentation once again.
https://pdir.de/docs/de/contao/extensions/socialfeed/configuration/

**Comment by petersku** [comment]
same issue with the facebook connection. (version 2.9.0 with contao 4.9.13.)
1. i have created a new FB app exactly as described in the documentation
2. when i save in contao the social feed account (with the option "generate access token") i can connect to the fb page as shown in the screens 
3. when i finished the connection i return to contao but the access token is not filled (no error message or something else) 

I also tried this with an fb testapp. same behavior.

**Comment by mikaser** [comment]
I have the same issue as petersku.
In the console I got "XMLRequest cannont load due to access comtrol checks".
Are there any news? Thx!

**Comment by cmartin6** [comment]
Is this fixed with version 2.9.1?

**Comment by petersku** [comment]
Hello Martin,
updated to 2.9.1. Same behavior. After saving (with the option "generate access token"), the access token isn´t filled. 
In the logs i get the error: "Error validating access token: The session is invalid because the user logged out."

**Comment by mosomork** [comment]
Same here – no new instagram posts in existing install. „last import date“ is updated correctly + access token ok

Contao: 4.9.16 / 4.9.19, Social Feed 2.9.1

LOG: request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function Pdir\SocialFeedBundle\Importer\Importer::getInstagramPosts(), 2 passed in /var/xxxx/vendor/pdir/social-feed-bundle/src/EventListener/CronListener.php on line 52 and exactly 3 expected" at /xxx/vendor/pdir/social-feed-bundle/src/Importer/Importer.php line 29 {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Pdir\\SocialFeedBundle\\Importer\\Importer::getInstagramPosts(), 2 passed in /xxx/pdir/social-feed-bundle/src/EventListener/CronListener.php on line 52 and exactly 3 expected at /xxx/vendor/pdir/social-feed-bundle/src/Importer/Importer.php:29)"} []
security.INFO: Populated the TokenStorage with an anonymous Token. []

**Comment by rburch** [comment]
Yeah I'm having a similar issue with Instagram. Everything was working up until a month ago. This is the error I get.

Too few arguments to function Pdir\SocialFeedBundle\Importer\Importer::getInstagramPosts(), 2 passed in /home/ampersand/public_html/vendor/pdir/social-feed-bundle/src/EventListener/CronListener.php on line 52 and exactly 3 expected

**Comment by SimonSpi** [comment]
Regarding the error discussed above:
The missing argument is in CronListener.php on line 52. The method getInstagramPosts expects an integer which acually seems to limit the maximum number of posts imported at that time. The parameter is further passed to the InstagramClient class 
(see InstagramClient.php, line 102) method getMediaData and there used for the REST call to the Instagram API. For me it is unclear if it was the intention to have the limiting number as a configuration parameter on the backend or at least in a configuration file. Thus I actually will not provide a proposal for a fix here. For my installation I manually fixed it quick and dirty with a hard coded limiting number in CronListener.php.

**Comment by MDevster** [comment]
fixed in version 2.9.3
