### ISSUE TITLE
Instagram Cronjob doesn't work 

### ISSUE THREAD

**Issue by Urtgard** [pdir/social-feed-bundle#66]
## Bug description
CronListener calls $objImporter->getInstagramPosts with only 2 instead of 3 arguments.

## Steps to reproduce
Setup a new instagram account with a cronjob following the documentation: https://pdir.de/docs/de/contao/extensions/socialfeed/configuration/instagram/

## Expected behavior
Cronjob loads instagram profile.

## Screenshots
![image](https://user-images.githubusercontent.com/13890391/132135528-77f96594-e879-464d-9a21-d0ac2c53b3dd.png)

## Bundle Version
Social Feed 2.9.1

## Environment
PHP 7.4 
Contao 4.9.20

**Comment by MDevster** [comment]
fixed in version 2.9.2
