### ISSUE TITLE
Instagram - Emojis displayed as ???

### ISSUE THREAD

**Issue by cmartin6** [pdir/social-feed-bundle#69]
## Bug description
If there are emojis in the post caption, the social-feed-bundle seems to convert these into question marks.

## Steps to reproduce
Import posts from instagram via the social-feed-bundle, which contain emojis in the caption

## Bundle Version
2.8.5

## Environment
Contao 4.9.20

**Comment by MDevster** [comment]
Please check your database encoding. 
See https://adamhooper.medium.com/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

**Comment by cmartin6** [comment]
tl_news, the table which gets filled with the posts actually is set to `utf8mb4_unicode_ci` 
Any other suggestions/ideas?

**Comment by cmartin6** [comment]
Nevermind - it works after setting the right encoding for the whole table - thank you @MDevster ;-)
