### ISSUE TITLE
ErrorException: Manually Facebook import

### ISSUE THREAD

**Issue by mpitz** [pdir/social-feed-bundle#71]
## Bug description
If you try to import the news manually via the moderated option in the news archive you'll get an ErrorException if you're in Contao debug mode.

## Screenshots
![image](https://user-images.githubusercontent.com/6831223/142990172-38631a81-5707-4a81-a673-c771474dad94.png)

## Bundle Version
2.9.2

**Comment by MDevster** [comment]
fixed in version 2.9.3, but manually Facebook import currently not supported. Maybe will be available in any next release.
