### ISSUE TITLE
LinkedIn doesn't allow Social Feeds

### ISSUE THREAD

**Issue by MarkejN** [pdir/social-feed-bundle#74]
First of all, I was happy to see the new LinkedIn Integration, thank you for the effort!
I followed your documentation, created a LinkedIn developer account and requested product access to the Marketing Developer Platform. However, my request was rejected with reference to this link: https://docs.microsoft.com/en-us/linkedin/marketing/restricted-use-cases#unapproved-use-cases

> Additional use cases we do not permit:
No Social Feeds: Under our MDP Terms, none of the data provided via our Page Management APIs can be used in a social feed use case (e.g. to display a feed of LinkedIn company updates on the company’s website or intranet).

Apparently, they no longer allow apps to create social walls using the API. Did I miss something, or can you confirm that as well?

**Comment by seibtph** [comment]
For example, you can write that the news articles should automatically be published on LinkedIn. I tested it with a new app and it worked.

![screenshot-customervoice microsoft com-2021 12 22-14_52_59](https://user-images.githubusercontent.com/17127525/147103616-7e98b64b-d723-4a38-b819-fb94b29f2cb3.png)
