### ISSUE TITLE
Erweiterung importiert fremde Posts

### ISSUE THREAD

**Issue by maniaxatwork** [pdir/social-feed-bundle#76]
Hallo, 
bisher hat alles prima funktioniert.

Heute ist meinem Chef allerdings aufgefallen, dass Sie Posts auf unsere Seite setzt, die gar nicht von unserer kommen,
Wir wurden in den fremden Posts lediglich erwähnt, und haben über Facebook auch keinen Zugriff auf die Seiten.

Ist da was bei meinen Einstellung schief gelaufen, ist FB schuld oder woran liegt das?

![Screenshot 2022-01-12 at 17-04-24 maniax-at-work Die Agentur für Macher](https://user-images.githubusercontent.com/40065105/149176635-5342b1a5-8791-4216-9564-cd225e67ed59.png)

der mittlere Beitrag ist von uns. die andere allerdings nicht,

**Comment by seibtph** [comment]
Hast du im Social Feed Account die Option "Nur Posts der Seite importieren" angehakt?

**Comment by dennisbohn** [comment]
Das Problem kann ich bestätigen. Heute wurde ein frischer Import angelegt und obwohl die Option "Nur Posts der Seite importieren" aktiviert wurde, werden auch Posts importiert, in denen der Feed lediglich erwähnt wurde.
