### ISSUE TITLE
Twitter PHP Exception

### ISSUE THREAD

**Issue by paddibr** [pdir/social-feed-bundle#78]
Hi,

ich bekomme neuerdings mit der neusten Version unter Contao 4.12.5 folgende Fehlermeldung:

`Twitter wird derzeit nicht unterstützt. Probiere Instagram aus.`

laut Logs:

`[2022-01-25T14:41:01.620394+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "file_get_contents() expects parameter 1 to be a valid path, null given" at /var/www/vhosts/xxx/contao/vendor/pdir/social-feed-bundle/src/EventListener/CronListener.php line 413 {"exception":"[object] (TypeError(code: 0): file_get_contents() expects parameter 1 to be a valid path, null given at /var/www/vhosts/xxx/contao/vendor/pdir/social-feed-bundle/src/EventListener/CronListener.php:413)"} []`

Ich habe mir die Keys neu generiert und eingetragen.

**Comment by seibtph** [comment]
Der manuelle Import über das News-Archiv geht aktuell nur mit Instagram. Funktioniert der Import über den Cronjob auch nicht?
