### ISSUE TITLE
Internal Server Error with new post on facebook

### ISSUE THREAD

**Issue by ScherzingerDMI** [pdir/social-feed-bundle#8]
After using the mate theme together with the social-feed-bundle for a few weeks without any errors in contao 4.4.36 we newly get an internal server error with a new post on facebook:

> Internal Server Error
> Was ist das Problem?
> 
> An exception occurred while executing 'INSERT INTO tl_news (`pid`, `singleSRC`, `addImage`, `tstamp`, `headline`, `teaser`, `date`, `time`, `published`, `pdir_sf_fb_id`, `pdir_sf_fb_account`, `pdir_sf_fb_account_picture`, `source`, `url`, `target`) VALUES ('8', 'D_XYZ_and_some_strange chars_', 1, 1554385524, 'Girls Day 2019: Was für ein toller Tag! 😍', 'Girls Day 2019: Was für ein toller Tag! <br>Gleich vier #girls durften wir heute bei uns begrüßen. Sie packten kräftig mit an und nahmen wichtige Erfahrungen und schöne Erinnerung mit nach Hause <br>Schön, dass ihr da wart! <br>#girlsday #girlsday2019 #mädchenzukunftstag #scherzinger #praktikum #ausbildung @ Scherzinger Pumpen GmbH & Co. KG', 1553789650, 1553789650, 1, '210274889016846_2389570927753887', 'Scherzinger Pumpen GmbH & Co. KG', 'l�and_some_other_strange chars_�', 'external', 'https://www.facebook.com/210274889016846/posts/2389570927753887/', 1)': SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x8D' for column `contao`.`tl_news`.`headline` at row 1

Unfortunatelly the contao-system is only available in our intranet so I can't give you a direkt link to the system. As I do not know, what further information you need for helping in this issue please contact me.
Thanks for every usefull hint and best regards!

**Comment by biwerr** [comment]
Seems like an issue with charset. 

https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

You could set the encoding to utf8mb4

**Comment by ScherzingerDMI** [comment]
Thanks biwerr! We use the charset utf8_unicode_ci - so also an utf8 charset.
But indeed the problem has to do something with the charset, because the smiley in the headline (''\xF0\x9F\x98\x8D' for column contao.tl_news.headline') caused the error - we removed it and now the error message disappeared.
Do you think that using utf8mb4 could solve the error in general if the mentioned smileys are used?
Thanks for your help!

**Comment by ScherzingerDMI** [comment]
Those who _can_ read have clearly an advantage ;-) and now also I read the link given by biwerr in detail: The answer to my issue is given there  ;-).
So I will change the UTF8 charset to the four byte version (utf8mb4)
Thanks again @biwerr !

**Comment by biwerr** [comment]
https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
