### ISSUE TITLE
Access token Popup nach "Zugriffsschlüssel anfordern" für managed_pages ?

### ISSUE THREAD

**Issue by sfx12** [pdir/social-feed-bundle#9]
Hallo,

ich habe Contao 4.4 und die neueste Version eures Plugins. Ich bin nach eurer Anleitung gegangen für die Generierung des access tokens: https://docs.pdir.de/#/social-feed/generierung-des-facebook-access-tokens.

Ich bin Admin einer Fanpage und möchte diesen feed auf der Homepage anzeigen.
Wenn ich nun eine neue app erstelle und dann den access token generieren möchte, kommt ein popup nach wahl der Berechtigung "manage_pages" in dem folgendes steht: 

FanpageXY erhält deinen Namen und dein Profilbild. FanpageXY kann nicht ohne deine Erlaubnis auf Facebook posten... wie ist das denn gemeint !? So wie ich das verstehe, wandelt der ja die Fanpage mit meinem privaten Profil um !?

In eurer Doku ist dieser Schritt nicht zu sehen!

Vielen Dank schon mal

**Comment by seibtph** [comment]
Ich habe es eben nochmal getestet. Scheinbar kann man nur noch einen Zugriffsschlüssel generieren, dessen Datenzugriff in etwa 3 Monaten abläuft. Mit der Anleitung scheint es zumindest nicht mehr zu gehen und eine Lösung habe ich dazu noch nicht gefunden.

Wenn du die Berechtigung "manage_pages" hinzufügst, öffnet sich ein Popup mit "Als XXX fortfahren" und anschließend wählst du deine entsprechende Seite aus, klickst auf Weiter und wählst bei "Deine Seiten verwalten" JA aus. Wenn du der Anleitung dann weiter folgst solltest du zumindest einen Access Token bekommen, der 3 Monate lang gültig ist.

**Comment by sfx12** [comment]
nein... :-( haben die das schon wieder geändert :-( bei instagram ja noch schlimmer da läusfts nach paar Tagen wieder ab...das ist echt doof - ich hätte es ja gerne meinen Kunden angeboten als Upgrade für deren Homepages.. aber bei 30-40 Stück alle 3 Monate neuen token generieren ist ja mehr als aufwendig! 

PS: Habe das mit "manage_pages" gemacht...leider spuckt mir facebook trotzdem eine Art Fehlermeldung das ein "review" notwendig ist als Unternehmen, die übertreiben echt langsam :-( Danke für deine Mühe!!!

**Comment by seibtph** [comment]
Ich werde nochmal schauen ob ich eine Lösung finde und dann wieder hier im Ticket antworten.

**Comment by sfx12** [comment]
Hallo, vielen Dank...ich habe nun eine App review als Einzelperson gemacht, danach bin ich die Prozedur anhand deiner Doku durchgegangen und siehe da, es hat funktioniert. Das war mit bestehenden apps die ich abgeändert habe, ich werde nun probieren die Sache mit einer neuen App zu erstellen.

PS: Wird es in naher Zukunft die Möglichkeit geben aich Instagram zu integrieren ?

**Comment by seibtph** [comment]
@sfx12 Hast du es denn schonmal mit einer neuen App probiert und etwas Neues herausgefunden? Ich habe es bisher noch nicht nicht geschafft einen Access Token zu generieren, der nie abläuft, allerdings auch noch nicht so viel Zeit da hinein investieren können.

Neue Features werden auf Kundenwunsch integriert. Auf unserer [Sponsoring-Seite](https://contao-themes.net/sponsoring.html?isorc=2) kannst du z. B. den Instagram Feed als Paket buchen und dann würden wir das in der nächsten Version veröffentlichen, inkl. Sponsoring-Erwähnung in der Readme des Social Feed Bundle. Beim Instagram-Feed wäre ein Access Token wie beim Facebook-Feed auch gar nicht nötig.

**Comment by sfx12** [comment]
Hallo Phillip,

tatsächlich hat es nun bei mir geklappt, ich musste beim facebook developer die einzelne app-review durchführen, somit konnte ich mit deinem tutorial einen unlimited token erstellen.

Zwei Fragen noch: wird es eine Weiterentwicklung zu dem feed geben, das z.B. auch die Events ausgelesen werden können ?

2. wenn ich die 150€ für das instagram post feed bezahle...ist das nur ne Art “spende” für die Weiterentwicklung oder ist dieses tool bereits entwickelt worden/finalisiert/einsetzbar ?

Danke. LG SfX12

**Comment by seibtph** [comment]
Danke für deinen Tipp, ich werde das mit der App mal probieren so wie du es beschrieben hast.

Das Auslesen der Facebook-Veranstaltungen wäre prinzipiell möglich. Ich habe auf der Sponsoring-Seite dafür ebenfalls noch ein Paket angelegt.

Wenn du 150 € für das Instagram Feed Feature bezahlen würdest, wird es auch defintiv umgesetzt und in der nächsten Version verfügbar sein. Es ist zu dem Zeitpunkt allerdings noch nicht finalisiert, wird aber dann zeitnah verfügbar sein.

**Comment by sfx12** [comment]
Mir fiel noch was auf: Contao importiert keine User Postings von Facebook. Kannst du das mal checken !? Danke!

**Comment by sfx12** [comment]
Sorry, zwecks import von Userposts, funktioniert es doch, ich war im falschen account ^^

**Comment by seibtph** [comment]
Also ich habe jetzt den einzelnen App Review durchgeführt und danach versucht den Access Token zu generieren, bekomme aber immer nur einen Token, dessen Datenzugriff nach 3 Monaten abläuft. Bei Ablaufdatum steht zwar "Niemals", bei Datenzugriff läuft ab steht dies aber nicht. Ist das bei dir anders? @sfx12

**Comment by seibtph** [comment]
Aber so wie ich das jetzt herausgefunden habe, läuft die Berechtigung "manage_pages" nicht ab, daher müsste es nach Ablauf des Datenzugriffs eigentlich auch noch funktionieren. 

https://developers.facebook.com/docs/facebook-login/auth-vs-data#data-access
