### ISSUE TITLE
Facebook Profilbild kann nicht geladen werden

### ISSUE THREAD

**Issue by BlackThunder22** [pdir/social-feed-bundle#92]
Hallo zusammen,

ich habe das Problem, dass unser Facebook-Profilbild nicht dargestellt werden kann, da der Zugriff verweigert wird:

![2022-10-24 22_23_11-Aktuelles - Ski- und Bergfreunde Haigerloch](https://user-images.githubusercontent.com/114856692/197621771-2c2653e7-5866-4347-b931-72fc00c30e98.png)

Seite: https://sbh-haigerloch.de/news.html 

Wenn ich den Pfad https://sbh-haigerloch.de/files/social-feed/sbhhaigerloch/172177694357.jpg in einem neuen Tab öffne kommt "403 Forbidden"

In der Contao Dateiverwaltung ist der Ordner "social-feed" öffentlich freigegeben.
Die Dateien im Themes-Ordner, welches sich ebenfalls unter "files" befindet, können auf der Seite anzeigt werden.
Die Bilder der Facebook-Artikel werden über "/assets/images/" aufgerufen, was funktioniert.

Hat jemand eine Idee?

**Comment by MDevster** [comment]
Klingt für mich nach einem Problem mit .htaccess Dateien die im Ordner über deiner Contao Installation liegen. Das passiert oft, wenn mehrere Domains in verschiedenen Ordner vorhanden sind oder die Installation nicht im Root Ordner erfolgt ist. Ohne weitere Infos oder Zugriff auf das System ist das aber schwer zu sagen.

**Comment by BlackThunder22** [comment]
Ich konnte das Problem nun lösen, indem ich per SSH die Rechte für alle Dateien und Verzeichnisse gesetzt habe, obwohl ich die Rechte für das genannte Verzeichnis per Filezilla bereits geprüft hatte. 
https://www.ninagerling.de/fachwissen/contao-nach-website-import-kein-aufruf-moeglich-403-forbidden.html
