### ISSUE TITLE
No styling applied - 403 error when scripts are loaded

### ISSUE THREAD

**Issue by breezyS** [pdir/social-feed-bundle#93]
## Bug description
I moved a Contao 4.4.57 installation from one provider to another and since then the social feed only shows up unstyled and all posts are in one column.

The console gives me some output:
`
GET /bundles/pdirsocialfeed/js/masonry.pkgd.min.js net::ERR_ABORTED 403
GET /bundles/pdirsocialfeed/js/imagesloaded.pkgd.min.js net::ERR_ABORTED 403

ausbildung.html:6862 
        
       Uncaught TypeError: $(...).imagesLoaded is not a function
    at HTMLDocument.<anonymous> (ausbildung.html:6862:40)
    at i (jquery-1.12.4.min.js:2:27449)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.min.js:2:28213)
    at Function.ready (jquery-1.12.4.min.js:2:30006)
    at HTMLDocument.K (jquery-1.12.4.min.js:2:30368)
`

## Steps to reproduce
This only happened after I moved the hosting provider, pdir settings remained untouched. Everything else works fine.

## Expected behavior
The Social Feed to be displayed with the usual styling.

## Bundle Version
2.8

## Environment
PHP7.4, Contao 4.4.57, ALL-INKL Hosting.

**Comment by MDevster** [comment]
After moving the installation you have to recreate the symlinks or run contao:setup again.
