### ISSUE TITLE
Not compatible with ContaoNewsBundle ^4.4

### ISSUE THREAD

**Issue by falkgeist** [pdir/social-feed-bundle#94]
The current DCA-Configuration for tl_news assumes existence of the palettes `article`, `external` and `internal`. These palettes have only been introduced since Contao 4.9.3, so in it's current state, the requirements in the composer.json would have to be changed to `^4.9.3`.

If trying to install the bundle in a Contao below that, the initializeScript throws the exception "Palette `article` not found in `tl_news`".

It would be much preferable though if the bundle would only add to those palettes if they exist, to keep compatibility with 4.4.

Sorry for not making a PR myself, I'm still figuring out, how to fix this and also how to properly make PRs.

**Comment by falkgeist** [comment]
Right now, I am just requiring 2.11, commenting out the lines for the three inexistent palettes in src/Resources/dca/tl_news and running `composer install`. This is not going to be update-safe, though.

**Comment by seibtph** [comment]
Fixed in Social Feed version 2.12.3
