### ISSUE TITLE
LinkedIn doesn't work

### ISSUE THREAD

**Issue by derkosmonaut** [pdir/social-feed-bundle#96]
We added the LinkedIn App and got the Access Token. But if we want to add the socialfeed to the news archive we got the error message: "LinkedIn is currently not supported. Try Instagram." The description of the plugin says: Currently supports Facebook, Instagram, Twitter and LinkedIn

**Comment by seibtph** [comment]
You can import posts automatically via cronjob. Only for instagram you can import posts manually in the news archive.
